name: Python package

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Generate Requirements.txt file
        uses: actions/setup-python@v5
      - name: Display Python version
        run: |
          - pip install virtualenv
          - python3 -m venv env
          - source env/bin/activate
          - pip3 install setuptools
          - python3 setup.py install
          - pip list --format=freeze > requirements.txt
          - ls -lah
      
          
          
